version: '3.8'

services:
  backend:
    build: ./PlaceFlow/backend
    env_file: .env.prod
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./PlaceFlow/frontend
    env_file: .env.prod
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always
