"""rename name to full_name

Revision ID: d0dbe9bf10e1
Revises: de3695a15c70
Create Date: 2026-05-24 20:39:26.354095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dbe9bf10e1'
down_revision: Union[str, Sequence[str], None] = 'de3695a15c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('admins', 'name')
    op.add_column('students', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'full_name')
    op.add_column('admins', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'full_name')
    # ### end Alembic commands ###
